networks:
    {{cookiecutter.project_slug}}-network:
        driver: bridge

services:
    nginx:
        extends:
            file: ./docker/services.compose.yml
            service: nginx
        depends_on:
            - {{cookiecutter.project_slug}}-frontend
        networks:
            - {{cookiecutter.project_slug}}-network

    llm:
        extends:
            file: ./docker/services.compose.yml
            service: llm
        networks:
            - {{cookiecutter.project_slug}}-network

    {{cookiecutter.project_slug}}-backend:
        extends:
            file: ./docker/services.compose.yml
            service: {{cookiecutter.project_slug}}-backend
        networks:
            - {{cookiecutter.project_slug}}-network

    {{cookiecutter.project_slug}}-frontend:
        extends:
            file: ./docker/services.compose.yml
            service: {{cookiecutter.project_slug}}-frontend
        networks:
            - {{cookiecutter.project_slug}}-network
