services:
  llm:
    extends:
      file: ./docker/services.compose.yml
      service: llm

  {{cookiecutter.project_slug}}-backend:
    extends:
      file: ./docker/services.compose.yml
      service: {{cookiecutter.project_slug}}-backend
    ports:
      - "8000:8000"